### ISSUE TITLE
官网很多链接都是502

### ISSUE THREAD

**Issue by yueyoum** [duoshuo/duoshuo-python-sdk#3]
好长时间了，

没人维护吗？

**Comment by shen2** [comment]
您能具体说说么？

**Comment by yueyoum** [comment]
登陆用户是好的， 非登陆用户 基本全部链接都是502。 两个月前是这样，现在不知道

**Comment by shen2** [comment]
嗯，现在应该修复了。

On Fri, Aug 16, 2013 at 4:25 PM, Wang Chao notifications@github.com wrote:

> 登陆用户是好的， 非登陆用户 基本全部链接都是502。 两个月前是这样，现在不知道
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/duoshuo/duoshuo-python-sdk/issues/3#issuecomment-22753825
> .

## 

Shen Zhenyu

School of Electronics Engineering and Computer Science, Peking University,
Beijing, 100871
Tel:+86-1381-177-7117
Homepage: shen2.tuchong.com
