### ISSUE TITLE
评论框的样式的问题

### ISSUE THREAD

**Issue by the5fire** [duoshuo/duoshuo-python-sdk#4]
你们最近是不是修改了评论部分，填写用户名和邮箱部分的样式。导致的结果是填入文字之后无法显示，我自己在博客上reset你们部分样式：

```
/*reset duoshuo */
#ds-wrapper #ds-reset .ds-control-group {
    max-width: 277px !important;
}
#ds-wrapper #ds-reset .ds-control-group input {
    padding: 4px 0px 6px 6px !important;
}
```

不知道是你们有修改样式，还是我升级css到bootstrap导致的。

另外，多说评论做的很赞！

**Comment by shen2** [comment]
你好，是由于你升级了bootstrap到3.0导致的，因为bootstrap3.0设置了
*{box-sizing:border-box}
导致盒模型出错。

目前我们已经修正了这个问题。你看一下不用自定义css能否正常显示？

**Comment by the5fire** [comment]
已经可以了，不错！
