### ISSUE TITLE
关于评论数和下面的评论不一致的情况

### ISSUE THREAD

**Issue by the5fire** [duoshuo/duoshuo-python-sdk#5]
之前在你们论坛也有提过这个问题，评论数和下面显示的评论不一致，有的是只有评论数，没有评论。不知道怎么破。

可以看我的这个文章，下面只有评论数没有评论内容：

http://www.the5fire.com/programmer-and-musician.html

过段时间还有这个问题的话，我就只好自己写评论模块了。

**Comment by perchouli** [comment]
sorry，这个项目创建比较早当时还没有watch所以我没收到通知。
这种情况发一条新评论刷新下数量就好了。

**Comment by the5fire** [comment]
@perchouli 没关系。

按照你说的方法还是不行。我在你们后台可以看到评论内容的。

**Comment by perchouli** [comment]
@AllenDingChen  小武给看看？这篇文章接口里是有数据的：
http://the5firecom.duoshuo.com/api/sites/listRecentPosts.json?num_items=10&require=site%2Cvisitor%2Cnonce%2CserverTime%2Clang&site_ims=1398042457&v=140327

**Comment by AllenDingChen** [comment]
谢花妈

Perchouli notifications@github.com编写：
