### ISSUE TITLE
python3 不能安装

### ISSUE THREAD

**Issue by DozenCoder** [duoshuo/duoshuo-python-sdk#8]
执行python setup.py install 就出现UnicodeDecodeError。
这个项目是不是没人维护了？

**Comment by perchouli** [comment]
环境是？python 3.5.2+mac 10.12.1 没重现这个错误。

**Comment by DozenCoder** [comment]
@perchouli Sorry, 刚看到。我是win8.1 python3.5.1 在powershell下安装提示：    

    PS F:\duoshuo-python-sdk> python .\setup.py install
    Traceback (most recent call last):    
      File ".\setup.py", line 8, in <module>  
        long_description=open('README.md').read(),  
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 105: illegal multibyte sequence
`

**Comment by perchouli** [comment]
read的时候python用了windows默认gbk编码，但文件是utf-8的。首行加上

`# -*- coding: utf-8 -*-`

或者把这行(L8)去掉吧，只是读取描述文件，不影响逻辑。

**Comment by DozenCoder** [comment]
谢谢啦，安装成功了。
